### ISSUE TITLE
Scapy importing

### ISSUE THREAD

**Issue by Ahmad-Chebbo** [omarrajab/NoJlede#1]
~/Desktop/NoJlede# python3 NoJlede.py 

Traceback (most recent call last):
  File "NoJlede.py", line 6, in <module>
    from scapy.all import *
ModuleNotFoundError: No module named 'scapy'

how can i solve this issue ?
i try to change the path of scapy into the python3 os.sys.path 
but also it's not working .

**Comment by omarrajab** [comment]
Hello,
Thank you for reporting this issue. You must install Scapy module
Using pip
Lunch the terminal type #pip install scapy.

Best Regards,
Omar Rajab.

**Comment by InfernoX0** [comment]
but already i have scapy on my kali :

~/Desktop/NoJlede# pip install scapy
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (2.4.2)
~/Desktop/NoJlede# python3 NoJlede.py 
Traceback (most recent call last):
  File "NoJlede.py", line 6, in <module>
    from scapy.all import *
ModuleNotFoundError: No module named 'scapy'

**Comment by omarrajab** [comment]
Hello,
I've Solved the issue on another computer ,python3 is required
you must download the following libraries for python3 : scapy and geocoder
#pip3 install scapy
#pip3 install geocoder

**Comment by Naushad007** [comment]
Hi Omar [Salaam]
Please check the error bellow, everything satisfied but i'm still getting error, hope you can help me... JZK

user123@host:~/NoJlede$ pwd
/home/user123/NoJlede
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ sudo pip3 install geocoder
Requirement already satisfied: geocoder in /usr/local/lib/python3.9/dist-packages (1.38.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from geocoder) (7.1.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from geocoder) (0.18.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from geocoder) (2.24.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from geocoder) (1.15.0)
Requirement already satisfied: ratelim in /usr/local/lib/python3.9/dist-packages (from geocoder) (0.1.6)
Requirement already satisfied: decorator in /usr/lib/python3/dist-packages (from ratelim->geocoder) (4.4.2)
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ sudo pip3 install scapy
Requirement already satisfied: scapy in /usr/lib/python3/dist-packages (2.4.4)
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ sudo python3 ./NoJlede.py 
Traceback (most recent call last):
  File "/home/user123/NoJlede/./NoJlede.py", line 6, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$ 
user123@host:~/NoJlede$
